branches:
  only:
  - master
  - preview
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
- 8.10.0
- 8.15.0
- 10.15.3
- 12.14.1
script: npm run build

jobs:
  include:
    - stage: npm release
      node_js: stable
      deploy:
        - provider: npm
          edge: true
          email: "$NPM_EMAIL"
          api_key: "$NPM_TOKEN"
          skip_cleanup: true
          tag: preview
          on:
            branch: preview
        - provider: npm
          edge: true
          email: "$NPM_EMAIL"
          api_key: "$NPM_TOKEN"
          skip_cleanup: true
          on:
            branch: master    

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/211513eb5775bf38f76e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always